"""Add notification_sent to Goal

Revision ID: f0d24dcce60a
Revises: 7e9ab3b5d518
Create Date: 2025-12-25 21:48:48.777381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d24dcce60a'
down_revision = '7e9ab3b5d518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')

    # ### end Alembic commands ###
